### ISSUE TITLE
'<div>' inside '<a>' element is moved outside on parsing

### ISSUE THREAD

**Issue by rbf** [cgrand/enlive#110]
As discussed in [this SO question](http://stackoverflow.com/a/1828032), [HTML 5](http://www.w3.org/TR/html5/text-level-semantics.html#the-a-element) states that

> the `<a>` element may be wrapped around entire paragraphs, lists, tables, and so forth, even entire sections, so long as there is no interactive content within (e.g. buttons or other links).

However, `enlive` puts block content outside (i.e. after) the `<a></a>` element. Here is a [MWE](http://www.minimalbeispiel.de/mini-en.html#x1-30002):

```clojure
;; Clojure 1.5.1
(require '[net.cgrand.tagsoup :as t])
;; => nil
(t/parser (java.io.StringReader. "<a href='#'>link<span>inline element</span></a>"))
;; => ({:tag :html, :attrs nil, :content ({:tag :body, :attrs nil, :content ({:tag :a, :attrs {:href "#"}, :content ("link" {:tag :span, :attrs nil, :content ("inline element")})})})})
(t/parser (java.io.StringReader. "<a href='#'>link<div>block element</div></a>"))
;; => ({:tag :html, :attrs nil, :content ({:tag :body, :attrs nil, :content ({:tag :a, :attrs {:href "#"}, :content ("link")} {:tag :div, :attrs nil, :content ("block element")})})})
```

Is that the intended behaviour?

I haven't found specific documentation or questions about that, so I'm raising a question here.

Might be related to the underlying [TagSoup parser](http://home.ccil.org/~cowan/tagsoup/).

**Comment by andrew-nguyen** [comment]
FYI, the hickory workaround doesn't appear to work if you're trying to modify :body.  I haven't looked much further but some quick debugging indicates that as-hickory returns only elements inside <head> and <body> but not <head> and <body> themselves.

**Comment by cgrand** [comment]
You just have to specify that you want to use the jsoup parser and not the
tagsoup one. You can specify that either per template or once per ns.

Le mercredi 28 janvier 2015, Andrew Nguyen <notifications@github.com> a
écrit :

> FYI, the hickory workaround doesn't appear to work if you're trying to
> modify :body. I haven't looked much further but some quick debugging
> indicates that as-hickory returns only elements inside
> and but not and themselves.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cgrand/enlive/issues/110#issuecomment-71872654>.
>


-- 
On Clojure http://clj-me.cgrand.net/
Clojure Programming http://clojurebook.com
Training, Consulting & Contracting http://lambdanext.eu/
