### ISSUE TITLE
zip-select vs select

### ISSUE THREAD

**Issue by alanpearce** [cgrand/enlive#117]
I've been trying to switch some of my code from using `select` to `zip-select`, as it now needs to be able to go back up the node tree, but the two functions aren't remotely alike and I ended up using a private function to get it working.

```clojure
(require '[net.cgrand.enlive-html :as html])
(require '[net.cgrand.xml :as xml])
(html/select (first (map xml/xml-zip (html/html-snippet "<div><p></p></div>"))) [:p])
(html/zip-select (map xml/xml-zip (html/html-snippet "<div><p></p></div>")) (list (@#'html/automaton [:p])))
```

Shouldn't `zip-select-nodes*` use `automaton` instead of `select-nodes*`? Also, I don't understand why `zip-select` uses apply for calling an arity-2 function with two args. Shouldn't it just call the function directly? Or am I doing things in completely the wrong way?

With both changes, I think that 
```clojure
(html/zip-select (map xml/xml-zip (html/html-snippet "<div><p></p></div>")) [:p])
```
would return a loc whose node is exactly the same as the original call to `select`, which seems like the least surprising way of working (excepting the removal of `first`, since `select` uses `as-nodes` but that doesn't bother me as much, although it would be nicer if they were the same.)

**Comment by justiniac** [comment]
Wouldn't that be a breaking change for existing programs? 
Please consider a discussion on the [group](https://groups.google.com/forum/#!forum/enlive-clj) and we may re-open the ticket. Thanks for the patch anyway!
