### ISSUE TITLE
From - Until Selector

### ISSUE THREAD

**Issue by BorisKourt** [cgrand/enlive#122]
This is not available directly in the CSS spec (although it may be possible after Selectors 4 hits), but I am wondering if this is possible to create here. 

I have output that looks like:
```html
<h1></h1>
<p></p>
<p></p>
<figure></figure>
<h1></h1>
<p></p>
<!-- and so forth -->
```
I want grab, and manipulate separately (i.e. wrap), everything between every `<h1>` tag. 

**Select *direct siblings* (` > *`) after `<h1>` until `<h1>` or EOF.**
or
**Select `<h1>` and *direct siblings* (` > *`) until `<h1>` or EOF**

Possible outcome:

```html
<h1></h1>
<div>
    <p></p>
    <p></p>
    <figure></figure>
</div>
<h1></h1>
<div>
    <p></p>
</div>
<!-- and so forth -->
```
or for the second example above:

```html
<div>
    <h1></h1>
    <p></p>
    <p></p>
    <figure></figure>
</div>
<div>
    <h1></h1>
    <p></p>
</div>
<!-- and so forth -->
```

**Comment by justiniac** [comment]
Please use [Enlive Google Group](https://groups.google.com/forum/#!forum/enlive-clj) to get help.
Will re-open if there's a problem with Enlive.
Thankies!
