### ISSUE TITLE
Enlive does not properly parse HTML5 docs with <meta> tags in the <body>

### ISSUE THREAD

**Issue by armhold** [cgrand/enlive#123]
Enlive does not properly parse HTML5 docs with `<meta>` tags in the `<body>`. This test fails, but will pass if you remove the `<meta>` tag:

```
(deftest test-enlive
  (testing "enlive"
    (let [html-as-string "<!DOCTYPE html><html lang=\"en\"><body><div><meta name=\"bar\"><span>the content</span></body></html>"
          parsed-html (enlive/html-resource (java.io.StringReader. html-as-string))
          span (enlive/select parsed-html [ :div  :span ])
          content (first (map enlive/text span))]
      (is (= "the content" content)))))
```

It also happens when I use the JSoup parser.

Stackoverflow issue: http://stackoverflow.com/questions/28335525/parsing-html5-with-enlive-tagsoup-jsoup

Old discussion on the mailing list: https://groups.google.com/forum/#!msg/enlive-clj/zjKsnL48Z6s/xoRJ_7PXwxYJ.

**Comment by armhold** [comment]
I tried running against JSoup directly and this works:

```
(deftest test-jsoup
  (testing "jsoup"
    (let [html-as-string "<!DOCTYPE html><html lang=\"en\"><body><div><meta name=\"bar\"><span>the content</span></body></html>"
          parsed-doc (soup/parse html-as-string)
          content (first (soup/text (soup/$ parsed-doc "div span")))]
      (is (= "the content" content)))))
```

**Comment by cgrand** [comment]
html-resource does not take ambient parser into account, you have to pass
explicit options

 (html-resource XXX (ns-options))

but then you stumble on an exception because jsoup/parser only accepts
InputStreams and not Readers so you have to (-> s (.getBytes "UTF-8")
java.io.ByteArrayInputStream.)

On Fri, Feb 6, 2015 at 3:36 AM, George Armhold <notifications@github.com>
wrote:

> I tried running against JSoup directly and this works:
>
> (deftest test-jsoup
>   (testing "jsoup"
>     (let [html-as-string "<!DOCTYPE html><html lang=\"en\"><body><div><meta name=\"bar\"><span>the content</span></body></html>"
>           parsed-doc (soup/parse html-as-string)
>           content (first (soup/text (soup/$ parsed-doc "div span")))]
>       (is (= "the content" content)))))
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cgrand/enlive/issues/123#issuecomment-73173590>.
>



-- 
On Clojure http://clj-me.cgrand.net/
Clojure Programming http://clojurebook.com
Training, Consulting & Contracting http://lambdanext.eu/

**Comment by armhold** [comment]
Thanks. The following works:

```
(deftest test-enlive
  (testing "enlive"
    (enlive/set-ns-parser! cgrand-jsoup/parser)
    (let [html-as-string "<!DOCTYPE html><html lang=\"en\"><body><div><meta name=\"bar\"><span>the content</span></body></html>"
          string-bytes (.getBytes html-as-string "UTF-8")
          bais (java.io.ByteArrayInputStream. string-bytes)
          parsed-html (enlive/html-resource bais (enlive/ns-options))
          span (enlive/select parsed-html [ :div  :span ])
          content (first (map enlive/text span))]
      (is (= "the content" content)))))
```

**Comment by cgrand** [comment]
beware : (enlive/ns-options) without argument returns a value for the
current namespace so is subject to dynamic binding. You should pass it an
argument or explicitely specifiy an option map.

On Fri, Feb 6, 2015 at 2:40 PM, George Armhold <notifications@github.com>
wrote:

> Thanks. The following works:
>
> (deftest test-enlive
>   (testing "enlive"
>     (enlive/set-ns-parser! cgrand-jsoup/parser)
>     (let [html-as-string "<!DOCTYPE html><html lang=\"en\"><body><div><meta name=\"bar\"><span>the content</span></body></html>"
>           string-bytes (.getBytes html-as-string "UTF-8")
>           bais (java.io.ByteArrayInputStream. string-bytes)
>           parsed-html (enlive/html-resource bais (enlive/ns-options))
>           span (enlive/select parsed-html [ :div  :span ])
>           content (first (map enlive/text span))]
>       (is (= "the content" content)))))
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cgrand/enlive/issues/123#issuecomment-73237403>.
>



-- 
On Clojure http://clj-me.cgrand.net/
Clojure Programming http://clojurebook.com
Training, Consulting & Contracting http://lambdanext.eu/

**Comment by LiFlash** [comment]
I just came across this issue, because I'm trying to crawl a 'well written' website. Since the default parser still seams not to handle html with a meta in the body, is this considered a feature? The above code works, but is a little verbose... I'm still a noob in webdevelopment, so please forgive my lack of understanding.
