### ISSUE TITLE
slightly strange ordering of parsed elements?

### ISSUE THREAD

**Issue by nicferrier** [cgrand/enlive#125]
```clojure
(let [xml-str "<a href='blah'>hello</a>
<a1:b>hi&nbsp;nic</a1:b>
<a href='blew'><div id='speshal'>a div</div></a>"
      tree (-> xml-str
               StringReader.
               enlive/html-resource)]
  (pprint (enlive/select tree [:body])))
```

produces this:

```
({:tag :body,
  :attrs nil,
  :content
  ({:tag :a, :attrs {:href "blah"}, :content ("hello")}
   "\n"
   {:tag :a1:b, :attrs nil, :content ("hi nic")}
   "\n"
   {:tag :a, :attrs {:href "blew"}, :content nil}
   {:tag :div, :attrs {:id "speshal"}, :content ("a div")})})
```

and I don't understand why the DIV is not a child of the second A

**Comment by nicferrier** [comment]
If you change the div to a span everything is good... which just looks like an error to me.

```clojure
(let [xml-str "<a href='blew'><span id='speshal'>a div</span></a>"
      tree (enlive/html-snippet xml-str)]
  ;; (enlive/select tree [:body])
  (pprint tree))
```

**Comment by pbwolf** [comment]
I don't think this is an issue with Enlive.  See the "Pluggable Parsers" bit on https://github.com/cgrand/enlive.  Enlive delegates to Tagsoup or JSoup to parse HTML.  Tagsoup apparently crammed the content into the HTML 4 mold.  In HTML 4, <A> could contain only inline content.[1]  On the other hand, Jsoup does what you expected.  (Except that it does not accept a Reader.)

(pprint (with-open [i (java.io.ByteArrayInputStream. (.getBytes "html etc etc"))] (html/html-resource i {:parser net.cgrand.jsoup/parser})))

[1] http://www.w3.org/TR/html401/struct/links.html#h-12.2

**Comment by justiniac** [comment]
See the [wiki](https://github.com/cgrand/enlive/wiki/JSoup-with-html-snippet) for a workaround on using JSoup with a Reader.
