### ISSUE TITLE
broken links in README.md

### ISSUE THREAD

**Issue by ed-g** [cgrand/enlive#126]
Looks like Brian's tutorial has been moved:

Old broken link. https://github.com/cgrand/enlive/wiki/Table-and-Layout-Tutorial,-Part-1:-The-Goal%20by%20Brian%20Marick

New link is https://github.com/cgrand/enlive/wiki/Table-and-Layout-Tutorial,-Part-1:-The-Goal

The syntax page does not load for me, the HTTP request times out.

http://enlive.cgrand.net/syntax.html

I found a copy on archive.org. https://web.archive.org/web/20120815210549/http://enlive.cgrand.net/syntax.html

**Comment by justiniac** [comment]
Tutorial and syntax now in the wiki.

**Comment by ed-g** [comment]
Links still broken in README.md. Would you accept patch to README with the new locations?

**Comment by justiniac** [comment]
Not pushed yet, be patient ;o)
