### ISSUE TITLE
Setting HTTP headers

### ISSUE THREAD

**Issue by kvn-prhn** [cgrand/enlive#150]
I am trying to scrape data from a website but need to change an HTTP header for it. Is there a way to change the headers in enlive? For example:

```
(defn fetch-url [url]
	(html/html-resource (java.net.URL. url) 
		[:User-Agent "User Agent Text" :Content-Type "text/plain"]))
(fetch-url "https://github.com")
```

**Comment by cgrand** [comment]
No, use an http client and pass the body to enlive.
