### ISSUE TITLE
flatten-nodes-coll (and thus clone-for) cannot accept integers

### ISSUE THREAD

**Issue by jevgeni** [cgrand/enlive#20]
using numbers as arguments for clone-for fail with exception:

```
user=> ((html/clone-for [item [2 3 4]] (fn [x] item)) :test-node)
(user=> java.lang.IllegalArgumentException: Don't know how to create ISeq from: java.lang.Integer
```
while using string are ok:

```
user=> ((html/clone-for [item ["2" "3" "4"]] (fn [x] item)) :test-node)
("2" "3" "4")
```
Quick troubleshooting shown, that this is flatten-nodes-coll is failing:

```
user=> (html/flatten-nodes-coll [1 2 3])
(user=> java.lang.IllegalArgumentException: Don't know how to create ISeq from: java.lang.Integer
```

**Comment by cgrand** [comment]
Nodes should be output and numbers are not nodes. So you should return a string and not a number. Enlive will support that when/if it grows support for user-controlled formatting.
