### ISSUE TITLE
Auto-reloading of templates

### ISSUE THREAD

**Issue by cgrand** [cgrand/enlive#6]

**Comment by kolov** [comment]
On my Macbook detecting a file change with the watch service used by net.cgrand.reload takes up to 8 seconds, so I came up with alternative polling solution (ring middleware), see https://github.com/kolov/enlive-reload. I've used it extensively on Mac OS Yosemite, no experience whatsoever on other platforms.

**Comment by justiniac** [comment]
Reload fixed in 1.1.6.
8 sec reload on Mac not experienced, rather in the order of 1 sec.
Closing for now, thankies!
