### ISSUE TITLE
Snippets adding <html><body> ?

### ISSUE THREAD

**Issue by magnars** [cgrand/enlive#93]
When using defsnippet, it adds `<html><body></body></html>` to the markup. Is this the intended behavior?

```clj
(defsnippet all-posts "templates/all-posts.html" [root] [posts] ...)
```

Aren't snippets meant to be used inside templates?

I worked around it by doing:

```clj
(defn snip [path]
  (html-snippet (slurp (io/resource path))))

(defsnippet all-posts (snip "templates/all-posts.html") [root] [posts] ...)
```

But either I've misunderstood how templates and snippets are supposed to work, or this is some weird behavior.

**Comment by justiniac** [comment]
Updated readme.
