### ISSUE TITLE
Fieldset nesting issue

### ISSUE THREAD

**Issue by DoodleIncident** [cgrand/enlive#95]
I was going though a clojurescript tutorial that uses enlive, and I ran into a strange bug related to form fieldsets. Using a page with a form with a fieldset results in the entire form being wrapped in a fieldset.

Test html and template:
https://gist.github.com/DoodleIncident/8895412  
https://gist.github.com/DoodleIncident/8895417  
And then I have a core.clj that just routes the post to the template.

Are fieldsets/labels just weird and strange and I shouldn't use them? I could easily give them up, this is just something I came across in my exploration of clojure and clojurescript.

**Comment by justiniac** [comment]
Please use [Enlive Google Group](https://groups.google.com/forum/#!forum/enlive-clj) to get help.
Will re-open if there's a problem with Enlive.
Thankies!
