### ISSUE TITLE
Html utf-8 can not be converted correctly

### ISSUE THREAD

**Issue by lhxws** [cgrand/enlive#97]
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>

        <title>Enlive Tutorial!</title>
    </head>
    <body>
        <p>你好!</p>
        <p id="message">A message could go here.</p>
    </body>
</html>

**Comment by justiniac** [comment]
Could you please discuss your issue on the [group](https://groups.google.com/forum/#!forum/enlive-clj)?
Thankies!
